async (page) => {
  const browser=page.context().browser();
  const c=await browser.newContext({viewport:{width:390,height:844},colorScheme:'dark',acceptDownloads:true});
  const p=await c.newPage(),errors=[],checks=[];
  p.on('pageerror',e=>errors.push(e.message));
  const unlock=async()=>{
    await p.locator('#settings').click();
    for(let i=0;i<7;i++)await p.locator('#app-version').click();
    if(await p.locator('#dialog').evaluate(d=>d.open))await p.locator('#dialog .dialog-head [data-action=close]').click();
  };
  const check=(ok,name)=>{if(!ok)throw new Error(name);checks.push(name);};
  const click=async action=>{
    const root=await p.locator('#dialog').evaluate(d=>d.open)?p.locator('#dialog'):p;
    await root.locator(`[data-action="${action}"]`).first().click();
  };
  const switchView=async v=>p.locator(`[data-view="${v}"]`).click();
  const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('botc-player-notebook-v1')));
  try{
    await p.goto('http://127.0.0.1:8794/');
    await p.locator('[data-action="new"]').first().waitFor();
    check(!await state(),'welcome does not create or overwrite a save');
    check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'welcome mobile fit');
    await click('demo');
    check(await p.locator('.player-card').count()===7,'demo has seven players');
    await unlock();
    check(!await state(),'demo isolated from real storage');
    check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'table mobile fit');
    await switchView('worlds');
    await p.locator('#solver-confirm').check();await click('analyze');
    await p.locator('.worlds-number').waitFor();
    check((await p.locator('.worlds-number').innerText()).trim()==='2','worker enumerates two demo worlds');
    check((await p.locator('#analysis-result').innerText()).includes('50'),'complete model displays world shares');
    check((await p.locator('#analysis-result').innerText()).includes('PAS des probabilités'),'explicit probabilities disclaimer');
    await click('clone-scenario');
    check(await p.locator('#scenario-select option').count()===2,'hypothesis cloning');
    await switchView('table');
    await p.locator('.player-open').first().click();
    await click('claim');
    await p.locator('[data-checkrole="chef"]').check();
    await p.locator('#claim-form button[type=submit]').click();
    await p.locator('.player-open').first().click();
    check((await p.locator('#dialog').innerText()).includes('Lavandière'),'claim history retained');
    await click('close');
    await p.locator('.thumb-hide').click();
    check(await p.locator('#cover').isVisible(),'privacy cover');
    await p.keyboard.press('Escape');
    check(await p.locator('#cover').isVisible(),'escape never reveals private notes');
    await p.keyboard.press('Tab');
    check(await p.locator('#uncover').evaluate(e=>e===document.activeElement),'cover traps keyboard focus');
    await p.locator('#uncover').click();
    await p.locator('#settings').click();
    await p.locator('#language').selectOption('en');
    await click('close');
    check((await p.locator('#nav').innerText()).includes('Hypotheses'),'English navigation');
    await switchView('script');
    await p.locator('#role-search').fill('empath');
    check(await p.locator('.role').count()===1,'bilingual script search');
    await p.locator('#settings').click();
    await p.locator('#language').selectOption('fr');
    await click('new');
    await p.locator('[name=title]').fill('Partie browser');
    await p.locator('[name=names]').fill('Alice\nBruno\nChloé\nDavid\nEmma\nFarid\nGaëlle');
    await p.locator('#new-form button[type=submit]').click();
    if(await p.locator('#dialog .onboarding').count())await p.locator('#dialog .dialog-head [data-action=close]').click();
    await unlock();
    let g=await state();
    check(g?.title==='Partie browser'&&g.players.length===7,'create persistent real notebook');
    const original=g.id;
    await click('claim');
    await p.locator('[data-checkrole="chef"]').check();
    await p.locator('#claim-form button[type=submit]').click();
    g=await state();
    check(g.claims.length===1&&Object.keys(g.scenarios[0].domains).length===0,'claim does not become solver fact');
    await p.locator('.player-card .player-open').first().click();
    await click('observe');
    await p.locator('[data-pickplayer]').nth(1).click();
    await p.locator('[name=value]').fill('1');
    await p.locator('[name=text]').fill('<img src=x onerror=alert(1)> direct testimony');
    await p.locator('#observation-form button[type=submit]').click();
    await switchView('journal');
    check(await p.locator('#journal-entries img').count()===0,'notes render inert text');
    check((await p.locator('#journal-entries').innerText()).includes('<img src=x'),'user text preserved');
    await switchView('table');
    await p.locator('.player-open').first().click();
    await click('execution');await p.locator('#round-form button[type=submit]').click();
    check((await state()).players[0].alive,'execution does not kill');
    await p.locator('.player-open').first().click();
    await click('life');
    check(!(await state()).players[0].alive,'explicit death saved');
    if(await p.locator('#dialog').evaluate(d=>d.open))await p.locator('#dialog .dialog-head [data-action=close]').click();
    await p.locator('#undo').click();
    check((await state()).players[0].alive,'undo restores prior state');
    await p.locator('#settings').click();
    const [download]=await Promise.all([p.waitForEvent('download'),click('export')]);
    const downloadPath=await download.path();
    check(download.suggestedFilename().endsWith('.json'),'JSON export download');
    await click('demo');
    check((await state()).id===original,'demo preserves existing real game');
    await p.reload();
    await p.locator('.player-card').first().waitFor();
    check((await p.locator('main h1').innerText())==='Partie browser','reload restores real game, not demo');
    await p.locator('#settings').click();await click('restore');
    await p.locator('#restore-file').evaluate(input=>{
      const files=new DataTransfer();
      files.items.add(new File(['{"version":99}'],'bad.json',{type:'application/json'}));
      input.files=files.files;
      input.dispatchEvent(new Event('change',{bubbles:true}));
    });
    await p.locator('#form-error:not([hidden])').waitFor();
    check((await state()).id===original,'invalid import preserves game');
    await p.locator('#restore-file').setInputFiles(downloadPath);
    await p.locator('#confirm-action').click();
    check((await state()).id===original,'round trip exported notebook');
    await switchView('worlds');await click('domain');
    await p.locator('[data-pick="chef"]').click();await p.locator('#domain-save').click();
    check((await state()).scenarios[0].domains[(await state()).players[0].id][0]==='chef','candidate selection persisted');
    await click('constraint');
    await p.locator('#constraint-players [data-pickplayer]').nth(1).click();
    await p.locator('#constraint-players [data-pickplayer]').nth(2).click();
    await p.locator('#constraint-roles [data-pick="imp"]').click();
    await p.locator('[name=note]').fill('Hypothèse personnelle');
    await p.locator('#constraint-form button[type=submit]').click();
    check((await state()).scenarios[0].constraints.length===1,'explicit relation saved');
    await p.locator('#solver-confirm').check();await click('analyze');
    await p.locator('.worlds-number, #analysis-result .error').waitFor();
    check((await p.locator('#analysis-result').innerText()).includes('Recherche incomplète'),'large search reports incomplete');
    check(await p.locator('#analysis-result .meter').count()===0,'no shares shown for incomplete search');
    await p.evaluate(async()=>{await navigator.serviceWorker.ready;});
    await p.reload();await p.locator('.player-card').first().waitFor();
    check(await p.evaluate(()=>!!navigator.serviceWorker.controller),'service worker controls app');
    await c.setOffline(true);
    check(await p.evaluate(async()=>{try{await fetch('/uncached-proof-'+Date.now());return false;}catch{return true;}}),'network genuinely unavailable');
    await p.reload();await p.locator('.player-card').first().waitFor();
    check(await p.locator('.player-card').count()===7,'offline reload restores notebook');
    await switchView('worlds');
    await p.locator('#solver-confirm').check();await click('analyze');
    await p.locator('.worlds-number, #analysis-result .error').waitFor();
    check((await p.locator('#analysis-result').innerText()).length>30,'worker executes offline');
    await p.goto('http://127.0.0.1:8794/guide.html');
    check((await p.locator('main h1').innerText()).includes('oracle'),'guide available offline');
    await c.setOffline(false);
    await p.goto('http://127.0.0.1:8794/');
    await p.locator('.player-card').first().waitFor();
    const other=await c.newPage();
    await other.goto('http://127.0.0.1:8794/');await other.locator('.player-card').first().waitFor();
    await other.locator('[data-action="claim"]').first().click();
    await other.locator('[data-checkrole="monk"]').check();
    await other.locator('#claim-form button[type=submit]').click();
    await p.locator('#banner').filter({hasText:'autre fenêtre'}).waitFor();
    check(await p.locator('#undo').isDisabled(),'cross-tab conflict locks writes');
    await other.close();
    check(errors.length===0,'no uncaught browser errors');
    return {checks:checks.length,passed:checks,errors};
  } finally {await c.close();}
}






